name: Tag Project

on:
  push:
    tags:
      - '*'

jobs:
  publish-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Build Project Artifact
        env:
          TAG: ${{ github.ref_name }}
        run: ./gradlew shadowJar -Ptag=${{ env.TAG }}

      - name: Publish Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        env:
          TAG: ${{ github.ref_name }}
        with:
          name: Tag - ${{ env.TAG }}
          path: build/libs/*.jar

      - name: Check Tag
        id: check-tag
        env:
          TAG: ${{ github.event.ref }}
        run: |
          if [[ ${{ env.TAG }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy Artifact
        if: steps.check-tag.outputs.match == 'true'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_HOST }}
          port: ${{ secrets.DEV_PORT }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_KEY }}
          source: build/libs/*.jar
          target: /opt/minecraft/data/plugins
          overwrite: true